substitutions:
  _REGION: asia-east1
  _IMAGE_TAG: 'latest'
  _PROJECT_ID: froyo-436105
  _artifact_repository: froyo-back-artifact
  _image_name: froyo-back-server

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_artifact_repository}/froyo-back-server:${_IMAGE_TAG}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['echo', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_artifact_repository}/froyo-back-server:${_IMAGE_TAG}']

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_artifact_repository}/froyo-back-server:${_IMAGE_TAG}'

options:
  logging: CLOUD_LOGGING_ONLY
